language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "pypy"
 - "pypy3"
sudo: false
addons:
  apt:
    packages:
    - curl
    - zlib1g
    - zlib1g-dev
install: 
 - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install unittest2; fi
 - pip install pillow
script: tests/alltests.py
